name: Feature request
description: Have an idea to make Poolland better?
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What is your idea?
      description: Describe the problem or need you would like to address.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this feature important?
      description: 'For example: “I have to deal with this every day...”'
    validations:
      required: false
