# Poolland Android build settings
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
kotlin.daemon.jvmargs=-Xmx1024m
android.useAndroidX=true
android.enableJetifier=false
# These two flags are added by the Flutter template
android.newDsl=false
android.builtInKotlin=false
