/// Lightweight in-app English/Persian strings for the Android UI.
/// Stored data (customer names, notes, user-defined labels) is never translated.
class AppLocalization {
  static String languageCode = 'fa';

  static const Map<String, String> _fa = {
    'Preparing the app…': 'در حال آماده‌سازی برنامه…',
    'App startup failed': 'راه‌اندازی برنامه ناموفق بود',
    'The local database could not be opened. Please try again.':
        'پایگاه دادهٔ محلی باز نشد. لطفاً دوباره تلاش کنید.',
    'Try again': 'تلاش دوباره',
    'Dashboard': 'داشبورد',
    'Personal': 'شخصی',
    'Customers': 'مشتریان',
    'Subscriptions': 'اشتراک‌ها',
    'Transactions': 'تراکنش‌ها',
    'Reports': 'گزارش‌ها',
    'Settings': 'تنظیمات',
    'Business': 'کسب‌وکار',
    'VPN business': 'کسب‌وکار VPN',
    'Record this in': 'ثبت در کدام بخش؟',
    'Choose where this transaction belongs before recording':
        'پیش از ثبت، مشخص کنید این تراکنش متعلق به کدام بخش است',
    'All': 'همه',
    'Save': 'ذخیره',
    'Cancel': 'انصراف',
    'Add': 'افزودن',
    'Edit': 'ویرایش',
    'Delete': 'حذف',
    'Close': 'بستن',
    'Search': 'جست‌وجو',
    'Done': 'انجام شد',
    'Confirm': 'تأیید',
    'Continue': 'ادامه',
    'Next': 'بعدی',
    'Previous': 'قبلی',
    'None': 'هیچ‌کدام',
    'Never': 'هرگز',
    'Today': 'امروز',
    'This month': 'این ماه',
    'Next month': 'ماه بعد',
    'Previous month': 'ماه قبل',
    'Next year': 'سال بعد',
    'Previous year': 'سال قبل',
    'Hello 👋': 'سلام 👋',
    'What would you like to do?': 'چه کاری می‌خواهید انجام دهید؟',
    'active subscriptions': 'اشتراک فعال',
    'Profit this month': 'سود این ماه',
    'Income': 'درآمد',
    'Expense': 'هزینه',
    'Sale': 'فروش',
    'Receive': 'دریافت',
    'Received': 'دریافت‌شده',
    'Refund': 'بازپرداخت',
    'Payment': 'پرداخت',
    'Sale / income': 'فروش / درآمد',
    'Customer payment': 'دریافت از مشتری',
    'Refund to customer': 'بازپرداخت به مشتری',
    'Payable settlement': 'تسویهٔ بدهی',
    'Payable payment': 'پرداخت بدهی',
    'Paid out': 'پرداخت‌شده',
    'Business receivables': 'مطالبات کسب‌وکار',
    'Business payables': 'بدهی‌های کسب‌وکار',
    'Business cash balance': 'موجودی نقد کسب‌وکار',
    'Cash balance': 'موجودی نقد',
    'Cash + bank': 'نقد و بانک',
    'Cash + collections': 'نقد و دریافتی‌ها',
    'Received this month': 'دریافتی این ماه',
    'Receivables': 'مطالبات',
    'Payables': 'بدهی‌ها',
    'Debtor': 'بدهکار',
    'Creditor': 'بستانکار',
    'debtors': 'بدهکار',
    'creditors': 'بستانکار',
    'All accounts are settled ✅': 'همهٔ حساب‌ها تسویه شده‌اند ✅',
    'By currency': 'به تفکیک ارز',
    'Balance': 'مانده',
    'Opening balance': 'ماندهٔ اول دوره',
    'Opening cash balance': 'موجودی نقد اولیه',
    'Opening cash balance (optional)': 'موجودی نقد اولیه (اختیاری)',
    'Amount': 'مبلغ',
    'Currency': 'ارز',
    'Date': 'تاریخ',
    'Description': 'شرح',
    'Description (optional)': 'شرح (اختیاری)',
    'Note': 'یادداشت',
    'Category': 'دسته‌بندی',
    'Income category': 'دسته‌بندی درآمد',
    'Expense category': 'دسته‌بندی هزینه',
    'Contact (optional)': 'مخاطب (اختیاری)',
    'Customer': 'مشتری',
    'Customer name...': 'نام مشتری…',
    'Select contact': 'انتخاب مخاطب',
    'Select customer': 'انتخاب مشتری',
    'New contact': 'مخاطب جدید',
    'New customer': 'مشتری جدید',
    'Phone number': 'شمارهٔ تلفن',
    'Call': 'تماس',
    'Telegram username (optional)': 'نام کاربری تلگرام (اختیاری)',
    'Message on Telegram': 'پیام در تلگرام',
    'Service name': 'نام سرویس',
    'Plan name': 'نام طرح',
    'Saved plan (optional)': 'طرح ذخیره‌شده (اختیاری)',
    'Price': 'قیمت',
    'Sale amount': 'مبلغ فروش',
    'Received now': 'مبلغ دریافتی',
    'Pay customer': 'پرداخت به مشتری',
    'Receive from customer': 'دریافت از مشتری',
    'Record income (no subscription)': 'ثبت درآمد (بدون اشتراک)',
    'Record expense': 'ثبت هزینه',
    'Personal expense': 'هزینهٔ شخصی',
    'Personal income': 'درآمد شخصی',
    'Payment / refund': 'پرداخت / بازپرداخت',
    'Sell a subscription': 'فروش اشتراک',
    'Record transaction': 'ثبت تراکنش',
    'Record this SMS transaction': 'ثبت این تراکنش پیامکی',
    'Manual transaction': 'تراکنش دستی',
    'New plan': 'طرح جدید',
    'Plans': 'طرح‌ها',
    'Plan': 'طرح',
    'Duration': 'مدت',
    'Duration:': 'مدت:',
    'Start': 'شروع',
    'Start date': 'تاریخ شروع',
    'End date (editable)': 'تاریخ پایان (قابل ویرایش)',
    'Auto-renew': 'تمدید خودکار',
    'Renew': 'تمدید',
    'Repeat interval': 'دورهٔ تکرار',
    'Monthly': 'ماهانه',
    'Weekly': 'هفتگی',
    'Daily': 'روزانه',
    'day': 'روز',
    'month': 'ماه',
    'Day of month:': 'روز ماه:',
    'Next due': 'سررسید بعدی',
    'Post due items': 'ثبت موارد سررسیدشده',
    'Active': 'فعال',
    'Archived': 'بایگانی‌شده',
    'Expiring soon': 'در آستانهٔ انقضا',
    'Expired': 'منقضی‌شده',
    'No subscriptions found': 'اشتراکی پیدا نشد',
    'No subscriptions recorded yet.': 'هنوز اشتراکی ثبت نشده است.',
    'No transactions yet': 'هنوز تراکنشی ثبت نشده است',
    'No transactions recorded.': 'تراکنشی ثبت نشده است.',
    'No transactions this month': 'این ماه تراکنشی ثبت نشده است',
    'Nothing recorded yet. Start with the buttons above.':
        'هنوز چیزی ثبت نشده است. از دکمه‌های بالا شروع کنید.',
    'Get started': 'شروع کنید',
    'Nothing awaiting review': 'موردی در انتظار بررسی نیست',
    'Nothing awaiting approval': 'موردی در انتظار تأیید نیست',
    'Quick add': 'افزودن سریع',
    'Quick-entry buttons': 'دکمه‌های ثبت سریع',
    'New button': 'دکمهٔ جدید',
    'Button label': 'عنوان دکمه',
    'Icon': 'آیکن',
    'Fixed amount (optional)': 'مبلغ ثابت (اختیاری)',
    'If left blank, the app will ask for an amount when recording.':
        'اگر خالی بماند، هنگام ثبت مبلغ از شما پرسیده می‌شود.',
    'Categories': 'دسته‌بندی‌ها',
    'Add category': 'افزودن دسته‌بندی',
    'Edit category': 'ویرایش دسته‌بندی',
    'Delete category': 'حذف دسته‌بندی',
    'Delete budget': 'حذف بودجه',
    'Monthly limit': 'سقف ماهانه',
    'Set a monthly limit for each category (such as food or transport); ':
        'برای هر دسته‌بندی (مثل خوراک یا رفت‌وآمد) سقف ماهانه تعیین کنید؛ ',
    'Budget': 'بودجه',
    'Appearance': 'نمایش',
    'System': 'طبق سیستم',
    'Light': 'روشن',
    'Dark': 'تیره',
    'Language': 'زبان',
    'فارسی': 'فارسی',
    'English': 'English',
    'Use Persian digits': 'استفاده از ارقام فارسی',
    'Business name': 'نام کسب‌وکار',
    'Basic data': 'اطلاعات پایه',
    'Display': 'نمایش',
    'Backups': 'نسخهٔ پشتیبان',
    'Data': 'داده‌ها',
    'Share backup': 'اشتراک‌گذاری پشتیبان',
    'Save backup to device': 'ذخیرهٔ پشتیبان در دستگاه',
    'Restore backup': 'بازیابی پشتیبان',
    'Restore from backup': 'بازیابی از پشتیبان',
    'All current data will be replaced with the contents of this file. Continue?':
        'همهٔ داده‌های فعلی با محتوای این فایل جایگزین می‌شوند. ادامه می‌دهید؟',
    'Current data will be erased and replaced with sample data. Continue?':
        'داده‌های فعلی پاک و با داده‌های نمونه جایگزین می‌شوند. ادامه می‌دهید؟',
    'All customers, subscriptions, and transactions will be deleted. Back up your data first.': 'همهٔ مشتریان، اشتراک‌ها و تراکنش‌ها حذف می‌شوند. ابتدا از داده‌ها پشتیبان بگیرید.',
    'Erase all data': 'پاک‌کردن همهٔ داده‌ها',
    'Load sample data': 'بارگذاری دادهٔ نمونه',
    'Sample data': 'دادهٔ نمونه',
    'Export CSV (spreadsheet)': 'خروجی CSV (صفحه‌گسترده)',
    'Export customers CSV': 'خروجی CSV مشتریان',
    'PDF report': 'گزارش PDF',
    'PDF statement': 'صورت‌حساب PDF',
    'Copy summary': 'کپی خلاصه',
    'Currencies and exchange rates': 'ارزها و نرخ تبدیل',
    'Add currency': 'افزودن ارز',
    'Remove currency': 'حذف ارز',
    'The base currency is Toman. Enter each currency’s rate in Toman to convert reports automatically.': 'ارز پایه تومان است. نرخ هر ارز را به تومان وارد کنید تا گزارش‌ها خودکار تبدیل شوند.',
    'Expiry reminders': 'یادآوری انقضا',
    'How many days before expiry should we remind you?':
        'چند روز پیش از انقضا یادآوری کنیم؟',
    'Expense reminder': 'یادآوری هزینه‌ها',
    'Reminder time': 'زمان یادآوری',
    'Reminds you every day at the selected time ':
        'هر روز در زمان انتخاب‌شده به شما یادآوری می‌کند ',
    'Check that notifications are displayed': 'نمایش اعلان‌ها را بررسی کنید',
    'Send test notification': 'ارسال اعلان آزمایشی',
    'SMS reading permission': 'دسترسی خواندن پیامک',
    'Read bank SMS': 'خواندن پیامک بانکی',
    'Grant SMS access': 'دادن دسترسی پیامک',
    'Android only': 'فقط اندروید',
    'Bank SMS': 'پیامک بانکی',
    'Review SMS': 'بررسی پیامک‌ها',
    'Sync': 'همگام‌سازی',
    'Rescan SMS': 'اسکن دوبارهٔ پیامک‌ها',
    'Reject': 'رد کردن',
    'Reject all': 'رد همه',
    'Reject all suggestions? ': 'همهٔ پیشنهادها رد شوند؟ ',
    'Review again': 'بررسی دوباره',
    'Manual SMS review is required': 'ثبت پیامک نیازمند بررسی دستی است',
    'Choose VPN business or personal before recording each SMS transaction.':
        'پیش از ثبت هر پیامک، کسب‌وکار VPN یا بخش شخصی را انتخاب کنید.',
    'Deposits and withdrawals are detected automatically ':
        'واریزها و برداشت‌ها خودکار شناسایی می‌شوند ',
    'SMS lookback period': 'بازهٔ بررسی پیامک‌ها',
    'How many past days should be checked?':
        'پیامک‌های چند روز گذشته بررسی شوند؟',
    'Poolland reminder test': 'آزمایش یادآور پول‌لند',
    'A simple offline ledger for VPN sellers\\nCustomers, balances, subscriptions, and real profit — all in one place': 'دفتر حساب آفلاین برای فروشندگان VPN\\nمشتریان، مانده‌ها، اشتراک‌ها و سود واقعی؛ همه در یک‌جا',
    'All data stays on this device\\nNo account and no internet required': 'همهٔ داده‌ها روی همین دستگاه می‌ماند\\nبدون حساب کاربری و بدون نیاز به اینترنت',
    'Try with sample data first': 'ابتدا دادهٔ نمونه را امتحان کنید',
    'Hidden from the main list': 'از فهرست اصلی پنهان است',
    'Archived plans are hidden from new sales.':
        'طرح‌های بایگانی‌شده در فروش‌های جدید نمایش داده نمی‌شوند.',
    'Delete this plan? Existing sales will not be changed.':
        'این طرح حذف شود؟ فروش‌های قبلی تغییر نمی‌کنند.',
    'Delete this subscription? (Financial transactions will remain.)':
        'این اشتراک حذف شود؟ (تراکنش‌های مالی باقی می‌مانند.)',
    'Delete this transaction?': 'این تراکنش حذف شود؟',
    'Delete customer': 'حذف مشتری',
    'Delete contact': 'حذف مخاطب',
    'Delete plan': 'حذف طرح',
    'Delete rule': 'حذف قانون',
    'Delete subscription': 'حذف اشتراک',
    'Delete transaction': 'حذف تراکنش',
    'Delete button': 'حذف دکمه',
    'Bank identifiers (for automatic SMS matching)':
        'شناسه‌های بانکی (برای تطبیق خودکار پیامک)',
    'Enter any existing balance here (for example, an old customer who owes 500,000).': 'ماندهٔ فعلی را وارد کنید (مثلاً مشتری قدیمی که ۵۰۰٬۰۰۰ تومان بدهکار است).',
    'Enter this customer’s last four card digits or full card number here, ':
        'چهار رقم آخر یا شمارهٔ کامل کارت مشتری را وارد کنید، ',
    '0912...': '۰۹۱۲…',
    '@username': '@نام‌کاربری',
    'e.g. 1 month, 50 GB': 'مثلاً ۱ ماه، ۵۰ گیگابایت',
    'e.g. 1-month unlimited - 2 devices': 'مثلاً نامحدود یک‌ماهه - ۲ دستگاه',
    'e.g. 1234, 6104********5678': 'مثلاً ۱۲۳۴، ۶۱۰۴********۵۶۷۸',
    'e.g. Alex VPN': 'مثلاً فروشگاه VPN من',
    'e.g. Home rent': 'مثلاً اجارهٔ خانه',
    'e.g. Taxi': 'مثلاً تاکسی',
    'e.g.': 'مثلاً',
    'Name': 'نام',
    'Title': 'عنوان',
    'Set up rent, internet, subscriptions, and salary once; ':
        'اجاره، اینترنت، اشتراک‌ها و حقوق را یک‌بار تنظیم کنید؛ ',
    'When on, record the charge first and enter any amount already settled below.': 'با فعال‌کردن، ابتدا کل هزینه ثبت می‌شود و مبلغ تسویه‌شده را در ادامه وارد می‌کنید.',
    'Customers, balances, subscriptions, and real profit — all in one place':
        'مشتریان، مانده‌ها، اشتراک‌ها و سود واقعی؛ همه در یک‌جا',
    'Subscription sales': 'فروش اشتراک',
    'Single-user configuration sales': 'فروش تنظیمات تک‌کاربره',
    'Subscription renewals': 'تمدید اشتراک',
    'Support and setup': 'پشتیبانی و راه‌اندازی',
    'Account and license sales': 'فروش اکانت و لایسنس',
    'Server / VPS purchase': 'خرید سرور / VPS',
    'Domain and SSL': 'دامنه و SSL',
    'Control panel and license': 'پنل مدیریت و لایسنس',
    'Advertising and marketing': 'تبلیغات و بازاریابی',
    'Payment gateway fees': 'کارمزد درگاه پرداخت',
    'Internet and work tools': 'اینترنت و ابزارهای کاری',
    'Salaries and wages': 'حقوق و دستمزد',
    'Other expenses': 'سایر هزینه‌ها',
    'Food and dining': 'خوراک و رستوران',
    'Transport and fuel': 'حمل‌ونقل و سوخت',
    'Housing and rent': 'مسکن و اجاره',
    'Utilities (water, electricity, gas)': 'قبوض (آب، برق، گاز)',
    'Internet and mobile top-up': 'اینترنت و شارژ موبایل',
    'Health and medical': 'سلامت و درمان',
    'Education': 'آموزش',
    'Leisure and entertainment': 'تفریح و سرگرمی',
    'Personal shopping and clothing': 'خرید شخصی و پوشاک',
    'Gifts and occasions': 'هدایا و مناسبت‌ها',
    'Sports and gym': 'ورزش و باشگاه',
    'Travel and trips': 'سفر و گردش',
    'Other personal expenses': 'سایر هزینه‌های شخصی',
    'Salary': 'حقوق',
    'Freelance income': 'درآمد آزادکاری',
    'Investment returns': 'سود سرمایه‌گذاری',
    'Gifts and support': 'هدیه و کمک‌هزینه',
    'Refunds and reimbursements': 'بازپرداخت و جبران هزینه',
    'Other personal income': 'سایر درآمدهای شخصی',
    '1 month, 50 GB': '۱ ماه، ۵۰ گیگابایت',
    '1 month, unlimited': '۱ ماه، نامحدود',
    '3 months, unlimited': '۳ ماه، نامحدود',
    'No customer': 'بدون مشتری',
    'Uncategorized': 'بدون دسته‌بندی',
    'Deleted category': 'دسته‌بندی حذف‌شده',
    'Included in business profit and loss':
        'در سود و زیان کسب‌وکار محاسبه می‌شود',
    'Excluded from business profit and loss':
        'در سود و زیان کسب‌وکار محاسبه نمی‌شود',
    'Income and expense categories': 'دسته‌بندی‌های درآمد و هزینه',
    'Auto-matched': 'تطبیق خودکار',
    'By category': 'به تفکیک دسته‌بندی',
    'No results found': 'نتیجه‌ای پیدا نشد',
    'All accounts': 'همهٔ حساب‌ها',
    'Personal only': 'فقط شخصی',
    'Business only': 'فقط کسب‌وکار',
    'Net profit': 'سود خالص',
    'Revenue': 'درآمد فروش',
    'Summary': 'خلاصه',
    'View all': 'نمایش همه',
    'See all': 'مشاهدهٔ همه',
    'Transactions awaiting review': 'تراکنش در انتظار بررسی',
    'transactions awaiting review': 'تراکنش در انتظار بررسی',
    'No new items found': 'مورد جدیدی پیدا نشد',
    'Grant access to identify incoming payments automatically':
        'برای شناسایی خودکار دریافتی‌ها دسترسی بدهید',
    'All data stays on this device': 'همهٔ داده‌ها روی همین دستگاه می‌مانند',
    'No account and no internet required':
        'بدون حساب کاربری و بدون نیاز به اینترنت',
    '(Auto-matched)': '(تطبیق خودکار)',
    'Record': 'ثبت',
    'Reminder only': 'فقط یادآوری',
    'To let Poolland read bank SMS and ': 'برای خواندن پیامک‌های بانکی و ',
    'months': 'ماه',
    'days': 'روز',
    'Deposit': 'واریز',
    'Withdrawal / purchase': 'برداشت / خرید',
    'Select': 'انتخاب',
    'Search...': 'جست‌وجو…',
    'Enter an amount': 'مبلغ را وارد کنید',
    'Credit': 'اعتباری',
    'Cash': 'نقدی',
    'Food': 'خوراک',
    'Transport': 'حمل‌ونقل',
    'Daily shopping': 'خرید روزانه',
    'Bills': 'قبوض',
    'Cafe': 'کافه',
    'Health': 'سلامت',
    '12-month summary': 'خلاصهٔ ۱۲ماهه',
    'About': 'دربارهٔ برنامه',
    'Daily reminder': 'یادآور روزانه',
    'Debtors': 'بدهکاران',
    'Expenses by category': 'هزینه‌ها به تفکیک دسته‌بندی',
    'Export': 'خروجی',
    'Income and expense trend': 'روند درآمد و هزینه',
    'Income sources': 'منابع درآمد',
    'Last 6 months': '۶ ماه گذشته',
    'Monthly budgets': 'بودجه‌های ماهانه',
    'Monthly income and expenses': 'درآمد و هزینهٔ ماهانه',
    'Recent personal transactions': 'تراکنش‌های شخصی اخیر',
    'Recent transactions': 'تراکنش‌های اخیر',
    'Recurring transactions': 'تراکنش‌های تکرارشونده',
    'Subscriptions expiring soon or expired':
        'اشتراک‌های نزدیک به انقضا یا منقضی‌شده',
    'Top customers this period': 'مشتریان برتر این دوره',
    'Inactive': 'غیرفعال',
    'Total purchases': 'جمع خریدها',
    'Total received': 'جمع دریافتی‌ها',
    'Activity': 'فعالیت',
    'All time': 'همهٔ زمان‌ها',
    'No plans yet': 'هنوز طرحی ثبت نشده است',
    'Choose a customer': 'انتخاب مشتری',
    'Select a plan': 'انتخاب طرح',
    'Choose category': 'انتخاب دسته‌بندی',
    'Record income': 'ثبت درآمد',
    'Could not load data': 'بارگذاری داده‌ها ناموفق بود',
    'Required': 'تکمیل این بخش الزامی است',
    'Enter a valid amount': 'مبلغ معتبر وارد کنید',
    'Payment recorded': 'پرداخت ثبت شد',
    'Transaction recorded': 'تراکنش ثبت شد',
    'Customer added': 'مشتری اضافه شد',
    'Saved': 'ذخیره شد',
    'Deleted': 'حذف شد',
    '{count} active subscriptions': '{count} اشتراک فعال',
    '{count} debtors': '{count} بدهکار',
    '{count} creditors': '{count} بستانکار',
    '{count} customers': '{count} مشتری',
    '{count} transactions': '{count} تراکنش',
    '{count} transactions awaiting review': '{count} تراکنش در انتظار بررسی',
    '{days} days before expiry': '{days} روز مانده تا انقضا',
    'Past {days} days': '{days} روز گذشته',
    'Select...': 'انتخاب…',
    'month(s)': 'ماه',
    'day(s)': 'روز',
    'Poolland Ledger': 'دفتر حساب پول‌لند',
    'Tomorrow': 'فردا',
    '{days} days left': '{days} روز تا انقضا',
    '{days} day ago': '{days} روز پیش',
    '{days} days ago': '{days} روز پیش',
    'billion': 'میلیارد',
    'million': 'میلیون',
    'thousand': 'هزار',
    'Personal summary — {month}': 'خلاصهٔ شخصی — {month}',
    '{from} to {to}': 'از {from} تا {to}',
    'Checking the past {days} days': 'در حال بررسی پیامک‌های {days} روز گذشته',
    'Delete customer "{name}" with {transactions} transactions and {subscriptions} subscriptions? This cannot be undone.': 'مشتری «{name}» همراه با {transactions} تراکنش و {subscriptions} اشتراک حذف شود؟ این کار برگشت‌پذیر نیست.',
    '{currency} exchange rate in Toman': 'نرخ تبدیل {currency} به تومان',
    'Remove {currency}? Existing transactions will not be deleted.':
        'ارز {currency} حذف شود؟ تراکنش‌های قبلی حذف نخواهند شد.',
    'Delete category “{name}”? Its transactions will become uncategorized.':
        'دسته‌بندی «{name}» حذف شود؟ تراکنش‌های آن بدون دسته‌بندی می‌شوند.',
    '{label} • {amount} recorded': '{label} • مبلغ {amount} ثبت شد',
    'Receive from': 'دریافت از',
    'Pay to': 'پرداخت به',
    'recorded': 'ثبت شد',
    'by': 'توسط',
    'days left': 'روز مانده',
    'Manage customers and balances': 'مدیریت مشتریان و مانده‌حساب‌ها',
    'Track each customer’s sales, payments, and balance in one place':
        'فروش‌ها، پرداخت‌ها و ماندهٔ هر مشتری را یک‌جا پیگیری کنید',
    'Subscriptions and expiry dates': 'اشتراک‌ها و تاریخ انقضا',
    'Automatic expiry reminders and one-tap renewals':
        'یادآوری خودکار انقضا و تمدید با یک لمس',
    'Real profit and reports': 'سود واقعی و گزارش‌ها',
    'Income, expenses, monthly profit, and top customers':
        'درآمد، هزینه‌ها، سود ماهانه و مشتریان برتر',
    'Multiple currencies': 'چندارزی',
    'Toman, US dollars, USDT, and any currency you add':
        'تومان، دلار، تتر و هر ارزی که اضافه کنید',
    'Enter a name': 'نام را وارد کنید',
    'Checking SMS...': 'در حال بررسی پیامک‌ها…',
    'No items found': 'موردی پیدا نشد',
    'Please wait': 'لطفاً صبر کنید',
    'No new transaction messages found. Tap Sync to check recent messages.':
        'پیامک تراکنش جدیدی پیدا نشد. برای بررسی دوباره، همگام‌سازی را بزنید.',
    'Tap + to record your first sale or expense.':
        'برای ثبت اولین فروش یا هزینه، دکمهٔ + را بزنید.',
    'Tap + to record a sale, receipt, or expense.':
        'برای ثبت فروش، دریافت یا هزینه، دکمهٔ + را بزنید.',
    'Plans are reusable sales templates (for example, “1 month, 50 GB”).\nCreate a plan to record a sale in seconds.': 'طرح‌ها الگوهای فروش قابل‌استفادهٔ مجدد هستند (مثلاً «۱ ماه، ۵۰ گیگابایت»).\nطرحی بسازید تا فروش را در چند ثانیه ثبت کنید.',
    'Yesterday': 'دیروز',
    'You have no quick buttons yet.': 'هنوز دکمهٔ ثبت سریعی ندارید.',
    'Manage': 'مدیریت',
    'A simple offline ledger for VPN sellers':
        'دفتر حساب آفلاین برای فروشندگان VPN',
    'A simple offline ledger for VPN sellers.':
        'دفتر حساب آفلاین برای فروشندگان VPN.',
    'Version 1.2.0 • Open-source software (MIT)':
        'نسخهٔ ۱.۲.۰ • نرم‌افزار متن‌باز (MIT)',
    'The Personal section is for your own finances and is not included in business profit or loss.': 'بخش شخصی برای امور مالی خودتان است و در سود و زیان کسب‌وکار محاسبه نمی‌شود.',
    'SMS access is not available on web or desktop. Try this feature on an Android phone.': 'دسترسی پیامک در وب یا رایانه فراهم نیست. این قابلیت را در تلفن اندرویدی امتحان کنید.',
    'To let Poolland read bank SMS and automatically identify deposits and withdrawals, grant SMS permission.\n\n• SMS messages are read on this device only\n• No data is sent anywhere\n• No transaction is recorded until you approve it': 'برای شناسایی خودکار واریز و برداشت، دسترسی خواندن پیامک بانکی را به پول‌لند بدهید.\n\n• پیامک‌ها فقط روی همین دستگاه خوانده می‌شوند\n• هیچ داده‌ای جایی ارسال نمی‌شود\n• تا زمانی که تأیید نکنید، تراکنشی ثبت نمی‌شود',
    'Subscriptions ({count})': 'اشتراک‌ها ({count})',
    'Transactions ({count})': 'تراکنش‌ها ({count})',
    '{who} {customer}': '{who} {customer}',
    'Last 1 month': 'ماه گذشته',
    'Last 3 months': '۳ ماه گذشته',
    'This year': 'امسال',
    'Settled': 'تسویه‌شده',
    'No subscription': 'بدون اشتراک',
    'No due items found': 'مورد سررسیدشده‌ای پیدا نشد',
    '{count} transactions recorded': '{count} تراکنش ثبت شد',
    'Delete the budget for “{category}”?': 'بودجهٔ «{category}» حذف شود؟',
    'Delete “{title}”? Existing transactions will remain.':
        '«{title}» حذف شود؟ تراکنش‌های قبلی باقی می‌مانند.',
    'Delete “{label}”?': '«{label}» حذف شود؟',
    'End: Never': 'پایان: هرگز',
    'End: {date}': 'پایان: {date}',
    'Last checked: {date}': 'آخرین بررسی: {date}',
    'Card {card}': 'کارت {card}',
    'Reference {reference}': 'شناسه {reference}',
    'Balance {balance}': 'مانده {balance}',
    '{amount} {status}': '{amount} {status}',
    '{name}\nBalance: {amount} {status}\nSubscriptions: {count}':
        '{name}\nمانده: {amount} {status}\nاشتراک‌ها: {count}',
    '{plan} • until {date}': '{plan} • تا {date}',
    '{amount} — cash or bank balance you already had':
        '{amount} — موجودی نقد یا بانکی که از قبل داشته‌اید',
    '{count} plans': '{count} طرح',
    '{count} categories (business and personal)':
        '{count} دسته‌بندی (کسب‌وکار و شخصی)',
    'The remaining balance will be recorded as customer debt: {amount}':
        'ماندهٔ باقی‌مانده به‌عنوان بدهی مشتری ثبت می‌شود: {amount}',
    'Base-currency equivalent at {rate} = {amount}':
        'معادل به ارز پایه با نرخ {rate} = {amount}',
    '{income} • {expense}': '{income} • {expense}',
    'Income {income} • Expense {expense}': 'درآمد {income} • هزینه {expense}',
    'This contact has {count} transactions. Deleting them will also delete all of those transactions. Continue?': 'این مخاطب {count} تراکنش دارد. با حذف او، همهٔ این تراکنش‌ها نیز حذف می‌شوند. ادامه می‌دهید؟',
    'Balance: {amount} (debtor)': 'مانده: {amount} (بدهکار)',
    'Balance: {amount} (creditor)': 'مانده: {amount} (بستانکار)',
    ' {count} transactions awaiting review': ' {count} تراکنش در انتظار بررسی',
    'Notification permission denied. Enable it in Android settings.':
        'اجازهٔ اعلان داده نشد. آن را در تنظیمات اندروید فعال کنید.',
    'Could not send notification': 'ارسال اعلان ناموفق بود',
    'Backup restored': 'پشتیبان بازیابی شد',
    'Invalid file: {error}': 'فایل نامعتبر است: {error}',
    'Details copied': 'جزئیات کپی شد',
    'Unknown bank': 'بانک ناشناس',
    'No quick buttons yet. Use “Manage” to add the buttons you need (food, taxi, bills...) and record expenses with one tap.': 'هنوز دکمهٔ ثبت سریعی ندارید. با «مدیریت» دکمه‌های دلخواه مثل خوراک، تاکسی و قبوض را اضافه کنید و با یک لمس هزینه را ثبت کنید.',
    'Set a monthly limit for each category (such as food or transport); this page will show how much of each limit remains.': 'برای هر دسته‌بندی مثل خوراک یا رفت‌وآمد سقف ماهانه تعیین کنید؛ اینجا ماندهٔ هر سقف نمایش داده می‌شود.',
    'Open': 'باز کردن',
    'No accounts are due': 'حساب سررسیدشده‌ای وجود ندارد',
    'Credits': 'اعتباری',
    'The report has been saved': 'گزارش ذخیره شد',
    'A report could not be created: {error}': 'ساخت گزارش ناموفق بود: {error}',
    'Setup failed: {error}': 'راه‌اندازی ناموفق بود: {error}',
    'Could not create file: {error}': 'ساخت فایل ناموفق بود: {error}',
    'Enter this customer’s last four card digits or full card number here, and incoming payments in bank SMS messages can be matched automatically.': 'چهار رقم آخر یا شمارهٔ کامل کارت این مشتری را وارد کنید تا دریافتی‌های پیامک بانکی به‌طور خودکار با او تطبیق داده شوند.',
    'Set up rent, internet, subscriptions, and salary once; the app will record them automatically on schedule.': 'اجاره، اینترنت، اشتراک‌ها و حقوق را یک‌بار تنظیم کنید تا برنامه در زمان‌بندی مشخص آن‌ها را خودکار ثبت کند.',
    'Deposits and withdrawals are detected automatically and added to the review queue':
        'واریزها و برداشت‌ها خودکار شناسایی و به صف بررسی اضافه می‌شوند.',
    'Reminds you every day at the selected time to record your expenses and income': 'هر روز در زمان انتخاب‌شده، ثبت هزینه‌ها و درآمدها را به شما یادآوری می‌کند.',
    'Reject all suggestions? (They will no longer appear, but no transactions will be deleted.)': 'همهٔ پیشنهادها رد شوند؟ دیگر نمایش داده نمی‌شوند، اما هیچ تراکنشی حذف نخواهد شد.',
    '{amount} {percent}': '{amount} {percent}',
    '{rank}. {customer}': '{rank}. {customer}',
    'Full period report with charts and transactions':
        'گزارش کامل این بازه همراه با نمودارها و تراکنش‌ها',
    'Transactions for this period': 'تراکنش‌های این بازه',
    'Enter a service name': 'نام سرویس را وارد کنید',
    'Income received': 'درآمد دریافت‌شده',
    'Profit margin': 'حاشیهٔ سود',
    'Received from customers': 'دریافت از مشتریان',
    'Cash paid': 'پرداخت نقدی',
    'Total receivables': 'کل مطالبات',
    'Total payables': 'کل بدهی‌ها',
    'Changes saved': 'تغییرات ذخیره شد',
    'Statement created': 'صورت‌حساب ساخته شد',
    'Sample data loaded': 'دادهٔ نمونه بارگذاری شد',
    'Could not create file': 'ساخت فایل ناموفق بود',
    'Nothing due': 'موردی سررسید نشده است',
    'Loading...': 'در حال بارگذاری…',
    'Archive plan': 'بایگانی طرح',
    'Archive': 'بایگانی',
    'This plan is used by existing subscriptions. It will be archived so renewals keep the correct duration.': 'این طرح در اشتراک‌های ثبت‌شده استفاده شده است. برای حفظ مدت تمدیدها، طرح بایگانی می‌شود.',
    'Edit contact': 'ویرایش مخاطب',
    'Save changes': 'ذخیرهٔ تغییرات',
    'Edit plan': 'ویرایش طرح',
    'Add plan': 'افزودن طرح',
    'Edit transaction': 'ویرایش تراکنش',
    'New transaction': 'تراکنش جدید',
    'Renew subscription': 'تمدید اشتراک',
    'Record renewal': 'ثبت تمدید',
    'Record sale': 'ثبت فروش',
    'Record receipt': 'ثبت دریافت',
    'Record payment': 'ثبت پرداخت',
    'Edit button': 'ویرایش دکمه',
    'Expenses': 'هزینه‌ها',
    'Cash received': 'نقد دریافتی',
    'Share': 'سهم',
    'Purchase amount': 'مبلغ خرید',
    'Transaction details': 'جزئیات تراکنش‌ها',
    'Type': 'نوع',
    'No transactions were recorded in this period.':
        'در این بازه تراکنشی ثبت نشده است.',
    'Financial and performance report': 'گزارش مالی و عملکرد',
    'Total debits': 'جمع بدهکار',
    'Total credits': 'جمع بستانکار',
    'Current balance (debit)': 'ماندهٔ جاری (بدهکار)',
    'Current balance (credit)': 'ماندهٔ جاری (بستانکار)',
    'Debit': 'بدهکار',
    'Page {page} of {pages}': 'صفحهٔ {page} از {pages}',
    'Generated with Poolland Ledger — page {page}':
        'ساخته‌شده با پول‌لند — صفحهٔ {page}',
    '{business} — Report {from} to {to}':
        '{business} — گزارش از {from} تا {to}',
    '{from} to {to} • Scope: {scope} • Issued: {issued}':
        'از {from} تا {to} • بازه: {scope} • تاریخ صدور: {issued}',
    'Statement for {customer}': 'صورت‌حساب {customer}',
    'Period: {from} to {to} • Issued: {issued}':
        'بازهٔ {from} تا {to} • تاریخ صدور: {issued}',
    'Phone: {value}': 'تلفن: {value}',
    'Note: {value}': 'یادداشت: {value}',
    'Positive balance = customer owes you  |  Negative balance = you owe the customer': 'ماندهٔ مثبت یعنی مشتری به شما بدهکار است | ماندهٔ منفی یعنی شما به مشتری بدهکارید',
    'Personal report': 'گزارش شخصی',
    'Toman': 'تومان',
    'US Dollar': 'دلار آمریکا',
    'Euro': 'یورو',
    'Personal transactions': 'تراکنش‌های شخصی',
    'Business transactions': 'تراکنش‌های کسب‌وکار',
    'Filter': 'فیلتر',
    'Sort': 'مرتب‌سازی',
    'Status': 'وضعیت',
    'Contact': 'مخاطب',
    'Customer statement': 'صورت‌حساب مشتری',
    'Payment for': 'پرداخت بابت',
    'Copy': 'کپی',
    'WhatsApp': 'واتس‌اپ',
    'Not now': 'فعلاً نه',
    'Unknown': 'نامشخص',
    'OK': 'باشه',
    'Yes': 'بله',
    'No': 'خیر',
    'Total': 'جمع',
    'Date range': 'بازهٔ زمانی',
    'From': 'از',
    'To': 'تا',
  };

  static String text(String source, {String? languageCode}) =>
      (languageCode ?? AppLocalization.languageCode) == 'fa'
      ? (_fa[source] ?? source)
      : source;

  static String format(
    String source,
    Map<String, Object?> values, {
    String? languageCode,
  }) {
    var result = text(source, languageCode: languageCode);
    for (final entry in values.entries) {
      result = result.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return result;
  }
}

extension LocalizedString on String {
  String get tr => AppLocalization.text(this);

  String trArgs(Map<String, Object?> values) =>
      AppLocalization.format(this, values);
}
